Areas/Admin/Controllers/GradeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using StudentManagement.Models;

namespace StudentManagement.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class GradeController : Controller
    {
        private readonly DataContext _context;

        public GradeController(DataContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var gdList = _context.Grades.OrderBy(g => g.GradeID).ToList();
            return View(gdList);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
                return NotFound();
            var gd = _context.Grades.Find(id);
            if (gd == null)
                return NotFound();
            return View(gd);
        }
        [HttpPost]

        public IActionResult Delete(int id)
        {
            var delGrade = _context.Grades.Find(id);
            if (delGrade == null)
                return NotFound();
            _context.Grades.Remove(delGrade);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Create()
        {
            var gdList = (from g in _context.Grades
                          select new SelectListItem()
                          {
                              Text = (g.GradeName != null) ? g.GradeName : "-- " + g.GradeName,
                              Value = g.GradeID.ToString()
                          }).ToList();
            gdList.Insert(0, new SelectListItem()
            {
                Text = "--- select ---",
                Value = "0"
            });
            ViewBag.gdList = gdList;
            return View();
        }
        [HttpPost]
        public IActionResult Create(tblGrade gd)
        {
            if (ModelState.IsValid)
            {
                _context.Grades.Add(gd);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(gd);
        }
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
                return NotFound();
            var gd = _context.Grades.Find(id);
            if (gd == null)
                return NotFound();

            var gdList = (from g in _context.Grades
                          select new SelectListItem()
                          {
                              Text = (g.GradeName != null) ? g.GradeName : "--" + g.GradeName,
                              Value = g.GradeID.ToString()
                          }

            ).ToList();
            gdList.Insert(0, new SelectListItem()
            {
                Text = "---select---",
                Value = "0"
            }
            );
            ViewBag.gdList = gdList;
            return View(gd);

        }
        [HttpPost]
        public IActionResult Edit(tblGrade gd)
        {
            if (ModelState.IsValid)
            {
                _context.Grades.Update(gd);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(gd);
        }
        
        [HttpPost]
        public async Task<IActionResult> ToggleStatus(int id)
        {
            var grade = await _context.Grades.FindAsync(id);
            if (grade == null)
                return NotFound();


            grade.IsActive = !grade.IsActive;
            _context.Update(grade);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

Areas/Admin/Views/Grade/Create.cshtml
@model StudentManagement.Models.tblGrade
@{
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<main id="main" class="main">
    <div class="pagetitle">
        <h2>Thêm khối</h2>
    </div>
    <div class="container shadow p-5">
        <form method="Post" asp-action="Create">
            <div class="form-row">
                <div class="form-group col-md-6 mb-3">
                    <lable>Tên khối</lable>
                    <input type="text" class="form-control" asp-for="GradeName" placeholder="Tên khối..." required>
                    <span asp-validation-for="GradeName" class="alert-danger"></span>
                </div>        

                <div class="form-group col-md-6 mb-3">
                    <label>Mô tả</label>
                    <input type="text" class="form-control" asp-for="Description"
                        placeholder="Nhập mô tả..." required>
                </div>
                
                <div class="form-group col-md-6 mb-3">
                    <label>
                        @Html.CheckBox("IsActive", false)
                    Hiện thị
                    </label>
                </div>
            </div>
            <a asp-controller="Grade" asp-action="Index" class="btn btn-lg btn-warning p-2">
                <i class="bi bi-arrow-left-circle"></i>
                Quay lại
            </a>

            <button type="submit" class="btn btn-lg btn-primary p-2">
                <i class="bi bi-file-plus-fill"></i> Lưu thông tin
            </button>
        </form>
    </div>
</main>

Areas/Admin/Views/Grade/Delete.cshtml
@model StudentManagement.Models.tblGrade

@{
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<main id="main" class="main">
    <div class="pagetitle">
        <h2>Xóa thông tin khối</h2>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label asp-for="GradeID">Mã khối</label>
            <input type="text" class="form-control mb-3" asp-for="GradeID" disaled />
        </div>
        <div class="form-group col-md-6">
            <label asp-for="GradeName">Tên khối</label>
            <input type="text" class="form-control mb-3" asp-for="GradeName" disaled />
        </div>
    </div>
    <!-- Begin Form -->
    <form asp-action="Delete" method="Post">
   
        <input type="hidden" asp-for="GradeID" />
        <a class="btn btn-lg btn-warning p-2 mr-5" href="javascript:history.back()">
            <i class="bi bi-arrow-left-circle"></i> Quay lại
        </a>
        <button type="submit" class="btn btn-lg btn-danger p-2">
            <i class="bi bi-trash"></i> Xóa
        </button>
    </form>
    <!-- End Form -->
</main>

Areas/Admin/Views/Grade/Edit.cshtml
@model StudentManagement.Models.tblGrade
@{
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<main id="main" class="main">
    <div class="pagetitle">
        <h2>Sửa thông tin khối</h2>
    </div>
    <div class="container shadow p-5">
        <form method="Post" asp-action="Edit">
            <div class="form-row">
                <input type="text" class="form-contro" asp-for ="GradeID" type="hidden">
                <div class="form-group col-md-6 mb-3">
                    <lable>Tên khối</lable>
                    <input type="text" class="form-control" asp-for="GradeName" placeholder="Tên khối...">
                    <span asp-validation-for="GradeName" class="alert-danger"></span>
                </div>
        
                <div class="form-group col-md-6 mb-3">
                    <label>Mô tả</label>
                    <input type="text" class="form-control" asp-for="Description"
                        placeholder="Nhập mô tả...">
                </div>
                                
                <div class="form-group col-md-6 mb-3">
                    <label>
                        @Html.CheckBox("IsActive",Model.IsActive)
                        Hiện thị
                    </label>
                </div>
            </div>
            <a asp-controller="Grade" asp-action="Index" class="btn btn-lg btn-warning p-2">
                <i class="bi bi-arrow-left-circle"></i>
                Quay lại
            </a>

            <button type="submit" class="btn btn-lg btn-primary p-2">
                <i class="bi bi-file-plus-fill"></i> Lưu thông tin
            </button>
        </form>
    </div>
</main>

Areas/Admin/Views/Grade/Index.cshtml
@using StudentManagement.Models;
@model IList<tblGrade>
@{
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<main id="main" class="main">
    <div class="pagetitle">
        <h2>Danh sách chức năng</h2>

        <p>

        <section class="section dashboard">
            <div class="row">
                <div class="col-12">
                    <div class="card recent-sales overflow-auto">
                        <div class="card-body mt-4">
                            <table class="table table-borderless datatable">
                                <thead>
                                    <tr>
                                        <th class="col-1 text-center">STT</th>
                                        <th class="col-1 text-center">Mã khối</th>
                                        <th class="col-1 text-center">Tên khối</th>
                                        <th class="col-1 text-center">Mô tả</th>
                                        <th class="col-1 text-center">Hiện thị</th>
                                        <th class="col-1 text-center">Chức năng</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @{
                                        int stt = 0; // 1. Khai báo và khởi tạo biến đếm
                                    }
                                    @foreach (var item in Model)
                                    {
                                        stt++; // 2. Tăng biến đếm cho mỗi mục
                                        <tr>
                                            <td class="text-center" scope="row">@stt</td>
                                            <td class="text-center" scope="row">@item.GradeID</td>
                                            <td class="text-left text-primary text-center" scope="row">
                                                <a asp-area="Admin" asp-controller="QLKhoi" asp-action="Details"
                                                    asp-route-id="@item.GradeID">
                                                    @item.GradeName
                                                </a>
                                            </td>
                                            <td class="text-center" scope="row">@item.Description</td>
                                            <td class="text-center">
                                                <form asp-area="Admin" asp-controller="Grade" asp-action="ToggleStatus"
                                                    method="post">
                                                    <input type="hidden" name="id" value="@item.GradeID" />
                                                    <div class="form-check form-switch d-flex justify-content-center">
                                                        <input class="form-check-input toggle-status-switch" type="checkbox"
                                                            name="IsActive" @(item.IsActive ? "checked" : "")
                                                            onchange="this.form.submit()" />
                                                    </div>
                                                </form>
                                            </td>

                                            <td class="text-center" scope="row">
                                                <a asp-area="Admin" asp-controller="Grade" asp-action="Edit"
                                                    asp-route-id="@item.GradeID" class="btn btn-primary btn-sm"
                                                    title="Edit the Grade"><i class="bi bi-pencil"></i></a>
                                                <a asp-area="Admin" asp-controller="Grade" asp-action="Delete"
                                                    asp-route-id="@item.GradeID" class="btn btn-danger btn-sm"
                                                    title="Delete the Grade"><i class="bi bi-trash"></i></a>

                                            </td>

                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        </p>


    </div>
</main>